### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by itsmeasik** [pharindoko/json-serverless#222]
The API gateway does not allow cross origin resource and I am getting issues. Could you guide me on how I can get over this issue.

**Comment by pharindoko** [comment]
Hi @itsmeasik,

I checked if I missed something.
So usually CORS is activated for the api gateway.
[cors activation in template](https://github.com/pharindoko/json-serverless/blob/a6083236339f662c7f053c7826599b4473fd5173/packages/cli/template/serverless.yml#L61)

Do you have a specific example for me, so I can test it ?

**Comment by itsmeasik** [comment]
Hi, thanks for the prompt response. this is the api gateway endpoint.
https://1n4nqxuwh9.execute-api.us-east-1.amazonaws.com/dev/api/categories/

i am able to do GET request to this endpoint but when i try POST, PUT or DELETE. I am getting the following error

`Access to XMLHttpRequest at 'https://1n4nqxuwh9.execute-api.us-east-1.amazonaws.com/dev/api/categories/ONGOING_ISSUES' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status`

I am successfully able to do GET, PUT, POST and DELETE through POSTMAN app. So I guess this is basically because of CORS.

**Comment by pharindoko** [comment]
Yes I assumed this already. :-/ I know this problem to good.
So which framework you are using for the frontend ?

**Comment by itsmeasik** [comment]
I am using angular as my front-end, can you suggest me something so that I can run it from aws. The local approach doesn't help in my use case.

**Comment by pharindoko** [comment]
Hi,

it seems to be still the same solution since angular 2 to use a proxy.json file.
https://www.positronx.io/handle-cors-in-angular-with-proxy-configuration/

**Comment by pharindoko** [comment]
#236

**Comment by itsmeasik** [comment]
Thanks a lot for looking into this at the earliest. I owe you a beer. :)

**Comment by pharindoko** [comment]
@itsmeasik 
So it works for you now ?
Can I close the issue ?

**Comment by itsmeasik** [comment]
No, the issue hasn't been fixed. 
I was acknowledging you for looking into it immediately.

**Comment by pharindoko** [comment]
> No, the issue hasn't been fixed.
> I was acknowledging you for looking into it immediately.
From backend side this is fixed. I will setup a small angular project as example when I have time.
As I said -this should work: https://www.positronx.io/handle-cors-in-angular-with-proxy-configuration/

**Comment by pharindoko** [comment]
@itsmeasik 
OK I understood the error now completey and had time to fix it.
Thanks a lot for your patience.
Please have a try.


**Solution:**
I removed the cors setting in api-gateway.

https://github.com/pharindoko/json-serverless/blob/a0c4d06d8ae61483fd957a0210a725f5c7dc6e9d/packages/cli/template/serverless.yml#L61


I would recommend to create a new api with the cli now 
```bash
npx json-serverless create-stack [JSON-File]
```

or to update your existing api:
1. change the property to cors: false in serverless.yml
2. update api
```bash
sls deploy
```

**Comment by itsmeasik** [comment]
Hi pharindoko, 

I tested it, but I am still facing the issues.

**Comment by pharindoko** [comment]
> Hi pharindoko,
> 
> I tested it, but I am still facing the same issues.

Hmm, ok I will take your json file and paste it into a new api and setup a sample.

**Comment by pharindoko** [comment]
1. git clone the sample
https://github.com/pharindoko/json-serverless-angular-test

2. Please create a new api first with the same jsonfile
```bash
npx json-serverless create-stack [JSON-File]
```

3. Add the new url to environment.ts in sample frontend
4. Start frontend
5. add new category

this worked for me

**Comment by itsmeasik** [comment]
Awesome, it works beautifully. 
Thanks a LOT.

**Comment by itsmeasik** [comment]
The issue reoccurred, I am getting CORS errors again. I guess AWS enables CORS after some time.
I am able to perform GET operation to go through but POST,PUT and DELETE are still blocked.

**Comment by pharindoko** [comment]
But you recreated it completely right ?

**Comment by itsmeasik** [comment]
Yeah, I created a new API and it worked for some time and then automatically it stopped working.

**Comment by pharindoko** [comment]
> Yeah, I created a new API and it worked for some time and then automatically it stopped working.

@itsmeasik 
I had an api newly created on 27th of January. I had the same issues you described. This is pretty weird.
And it event went better (ironic)... 
- When I was using an additional application in chrome to add the headers (x-api-key, content-type) it worked again.
- When I create a new api it works without any problems.

I try to figure it out. Maybe I have a wrong assumption in my head.

**Comment by pharindoko** [comment]
> > Yeah, I created a new API and it worked for some time and then automatically it stopped working.
> 
> @itsmeasik
> I had an api newly created on 27th of January. I had the same issues you described. This is pretty weird.
> And it event went better (ironic)...
> 
> * When I was using an additional application in chrome to add the headers (x-api-key, content-type) it worked again.
> * When I create a new api it works without any problems.
> 
> I try to figure it out. Maybe I have a wrong assumption in my head.

Ok - so I tried it for the new created API, which I created 5 days ago. It works without issues.
I did create it without api-authentication. I will try this as well to verify even there it works.
 
@itsmeasik 

> I guess AWS enables CORS after some time.

 -> I can`t believe this. you can check the api gateway settings - there must be an Options VERB added to the routes. I do not add this. Cors will be added internally by json-serverless-lib.

**Comment by pharindoko** [comment]
OK - found a solution and a assumption why the second approach runs into issues.
Reason was found in the serverless framework / serverless.yml

**This works:**
```
    events:
      - http:
          path: /
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: "{proxy+}"
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

```

**this generates in cloudformation-template-update-stack.json:**
```


          "IntegrationResponses": [
            {
              "StatusCode": "200",
              "ResponseParameters": {
                "method.response.header.Access-Control-Allow-Origin": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
                "method.response.header.Access-Control-Allow-Methods": "'OPTIONS,DELETE,GET,HEAD,PATCH,POST,PUT'"
              },
              "ResponseTemplates": {
                "application/json": ""
              }
            }
          ]
```





**This does not work:**

```
    events:
      - http:
          path: /
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors: true
      - http:
          path: "{proxy+}"
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors: true

```

**this generates in cloudformation-template-update-stack.json:**
```

              "ResponseTemplates": {
                "application/json": "#set($origin = $input.params(\"Origin\"))\n#if($origin == \"\") #set($origin = $input.params(\"origin\")) #end\n#if($origin.matches(\".*\")) #set($context.responseOverride.header.Access-Control-Allow-Origin = $origin) #end"
              }
```

Serverless Framework has it describe in this documentation:
https://serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors

Please note that since you can't send multiple values for Access-Control-Allow-Origin, this configuration uses a response template to check if the request origin matches one of your provided origins and overrides the header with the following code:

#set($origin = $input.params("Origin")
#if($origin == "http://example.com" || $origin == "http://*.amazonaws.com") #set($context.responseOverride.header.Access-Control-Allow-Origin = $origin) #end
Configuring the cors property sets Access-Control-Allow-Origin, Access-Control-Allow-Headers, Access-Control-Allow-Methods,Access-Control-Allow-Credentials headers in the CORS preflight response.

Please note that the Access-Control-Allow-Credentials-Header is omitted when not explicitly set to true.

**Comment by itsmeasik** [comment]
Thanks this works for now. Although I will have to test it out for few more days to figure out if this will continue working.

**Comment by pharindoko** [comment]
> Thanks this works for now. Although I will have to test it out for few more days to figure out if this will continue working.

I updated the npm package already. if you create a new stack this is already part of it.
If you want to update your stack you can as well use:

```
npx jsonserverless update-stack
```

**Comment by pharindoko** [comment]
@itsmeasik:
Thanks for the immediate feedback.
Please let me know if it worked for the next few days.

**Comment by pharindoko** [comment]
@itsmeasik 
Can I close the issue ?

**Comment by itsmeasik** [comment]
Still the same error.

**Comment by pharindoko** [comment]
Hey @itsmeasik,

I checked it again - it works for me 
1. Please verify that you have the newest version:

```bash
npm i -g json-serverless
jsonsls -v
```
result:
json-serverless/1.5.23 darwin-x64 node-v12.12.0

2. create a complete new api
```bash
jsonsls create-stack  {jsonfile} **-a**
```
3. use the basic angular project I made for this testcase
https://github.com/pharindoko/json-serverless-angular-test
In environment.ts you just need to replace values for url and optionally the apitoken (if **-a** will be used)

If this works we can close the issue.
If not I think I`m not able to help you.
