### ISSUE TITLE
no exported member 'CloudApp'

### ISSUE THREAD

**Issue by julien-von-oetinger** [pharindoko/json-serverless#349]
**Describe the bug**

Today I have tried to run "jsonsls update-stack" as I usually do but now I have an error message:

```
ERROR in /mnt/c/Users/Julien/Documents/greenmotion-frontend/api/api-server/src/handler.ts
./src/handler.ts
[tsl] ERROR in /mnt/c/Users/Julien/Documents/greenmotion-frontend/api/api-server/src/handler.ts(4,21)
      TS2305: Module '"../node_modules/json-serverless-lib/lib"' has no exported member 'CloudApp'.
```

When I open the the "handler.ts" file in my visual studio code, it complains about "CloupApp" that is not found in "json-serverless-lib". If I look in my node_modules, it really seems like this "CloupApp" is not available. 

I have tried restart everything from scratch but I still have the issue. Any idea ?

**Comment by pharindoko** [comment]
Hey, 

yes I have an idea. I released a major update  today and refactored the code.
Please ensure in anyway that you have the latest version when you test.

I will fix the update-stack function the next 1-3 days in anyway.

If you need it now please create a new stack.

br,

flo

**Comment by pharindoko** [comment]
@julien-von-oetinger 
Hey please test

**Comment by pharindoko** [comment]
@julien-von-oetinger 
I released a new version that should hopefully fix your issue.
Please test it.

**Comment by julien-von-oetinger** [comment]
Thanks for the quick update ! 👍 

Now the update stack works but when I try to reach the api url I get:

`{"message": "Internal server error"}`

In addition when I try to run the server locally with "jsonsls run db.json", I have the following error:

```
{"level":30,"time":1588629887966,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"environment: {\"basePath\":\"/\"}","v":1}{"level":30,"time":1588629888079,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"ValidationRule:                                        Result                                                                         Message","v":1}
{"level":30,"time":1588629888081,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"IsObjectRule:                                              OK                                                                                ","v":1}
{"level":30,"time":1588629888082,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasObjectKeyRule:                                          OK                                                                                ","v":1}
{"level":30,"time":1588629888083,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888083,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888084,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888085,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888086,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888086,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888088,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888090,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888091,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888091,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"HasIdAttributeRule:                                        OK                                                                                ","v":1}
{"level":30,"time":1588629888097,"pid":656,"hostname":"DESKTOP-UNT14RT","msg":"Init Swagger","v":1}
Error: Don't know how to handle schema {"format":"double","example":"46.5414426"} without type and schema
    at /usr/local/lib/node_modules/json-serverless/node_modules/swagger-to-graphql/lib/typeMap.js:59:15
    at Object.exports.jsonSchemaTypeToGraphQL (/usr/local/lib/node_modules/json-serverless/node_modules/swagger-to-graphql/lib/typeMap.js:60:7)
    at /usr/local/lib/node_modules/json-serverless/node_modules/swagger-to-graphql/lib/typeMap.js:79:32
    at Array.reduce (<anonymous>)
    at /usr/local/lib/node_modules/json-serverless/node_modules/swagger-to-graphql/lib/typeMap.js:76:40
    at resolveThunk (/usr/local/lib/node_modules/json-serverless/node_modules/graphql/type/definition.js:468:40)
    at defineFieldMap (/usr/local/lib/node_modules/json-serverless/node_modules/graphql/type/definition.js:667:18)
    at GraphQLObjectType.getFields (/usr/local/lib/node_modules/json-serverless/node_modules/graphql/type/definition.js:613:27)
    at collectReferencedTypes (/usr/local/lib/node_modules/json-serverless/node_modules/graphql/type/schema.js:366:81)
    at collectReferencedTypes (/usr/local/lib/node_modules/json-serverless/node_modules/graphql/type/schema.js:368:9)
```

I guess the "internal server error" is related to that.

**Comment by pharindoko** [comment]
Hey, 

there`s 2 things to mention:

1. I don`t know how private your data is. 
Can you post the file or send it directly to me (florian.fuss@freenet.de) for testing ?

2. I assume it must behave the same way when you run it locally, correct ?
```bash
jsonsls run {file}
```

**Comment by julien-von-oetinger** [comment]
The source of the problem was in fact in my db.json. I add something like this:

```
"latitude": 46.5414426,
"longitude": 6.6280342,
```

If I turn the double to strings:

```
"latitude": "46.5414426",
"longitude": "6.6280342",
```

The fun part is that I had those since months without any issue. 
Now I can run the database locally.

I still have an internal server error when I try to deploy into to AWS. I'm trying to find the logs.

**Comment by pharindoko** [comment]
> The source of the problem was in fact in my db.json. I add something like this:
> 
> ```
> "latitude": 46.5414426,
> "longitude": 6.6280342,
> ```
> 
> I have turned the double to string:
> 
> ```
> "latitude": "46.5414426",
> "longitude": "6.6280342",
> ```
> 
> The fun part is that I had those since months without any issue.
> Now I can run the database locally and on aws.

Hmm yeah reason is the new introduced interface with graphql....
I think I will add an option to deactivate this in future.

Another thing -> the float values you had are correct. 
That`s valid json so it should work. 

Will check it. I need more tests in anyway for the swagger and graphql generation....step by step....

Thanks for the update.

**Comment by pharindoko** [comment]
@julien-von-oetinger 
This should be fixed now. 
Please try...

**Comment by julien-von-oetinger** [comment]
Now it always fail with the following error:

```
{"level":30,"time":1588705958318,"pid":85,"hostname":"DESKTOP-UNT14RT","msg":"environment: {\"basePath\":\"/\"}","v":1}
{"level":30,"time":1588705958329,"pid":85,"hostname":"DESKTOP-UNT14RT","msg":"ValidationRule:                                        Result                                                                         Message","v":1}
{"level":30,"time":1588705958330,"pid":85,"hostname":"DESKTOP-UNT14RT","msg":"IsObjectRule:                                              OK                                                                                ","v":1}
{"level":30,"time":1588705958330,"pid":85,"hostname":"DESKTOP-UNT14RT","msg":"HasObjectKeyRule:                                       ALERT                          no root properties found - no endpoints can be created","v":1}
{"level":50,"time":1588705958331,"pid":85,"hostname":"DESKTOP-UNT14RT","msg":"provided json is not valid - see validation checks","v":1}
Error: provided json is not valid - see validation checks
    at CoreApp.<anonymous> (/usr/local/lib/node_modules/json-serverless/node_modules/json-serverless-lib/lib/app/core.app.js:95:31)
    at step (/usr/local/lib/node_modules/json-serverless/node_modules/json-serverless-lib/lib/app/core.app.js:33:23)
    at Object.next (/usr/local/lib/node_modules/json-serverless/node_modules/json-serverless-lib/lib/app/core.app.js:14:53)
    at fulfilled (/usr/local/lib/node_modules/json-serverless/node_modules/json-serverless-lib/lib/app/core.app.js:5:58)
```

I have even tried with the demo db.json for the instructions:

```
{
    "posts": [
      { "id": 1, "title": "json-server", "author": "typicode" },
      { "id": 2, "title": "test", "author": "yourAuthor" }
    ],
    "comments": [
      { "id": 1, "body": "some comment", "postId": 1 }
    ],
    "profile": { "name": "typicode" }
}
```

But still have the same error.

**Comment by pharindoko** [comment]
Hey I tested it and had no issues. 
It worked for different files.
I copy and pasted the samplecode from above and this worked too.

The validation failed because something in this json file does not fit. 
The objectkeyrule states that the json needs to be at root an object starting with {}.

The rules for the validation will be tested with unittests.
https://github.com/pharindoko/json-serverless/blob/582e3b290efd5160b09eb65bc0450f67bb2ad67a/packages/server/tests/validations.spec.ts#L35

Please verify you have the newest version 
```
npm i -g json-serverless
jsonsls -v
```

and run it locally first
```
jsonsls run db.json
```

**Comment by julien-von-oetinger** [comment]
Yes sorry it works for me too now. I don't know what I did yesterday night. I must have done a mistake. All good now 👍 ! Great job !

**Comment by pharindoko** [comment]
Thanks for contributing theses issues. Will close this issue for now.
